# Generated by Django 5.1.4 on 2025-02-13 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SharedCompliment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliments.compliment')),
            ],
        ),
    ]
