# Generated by Django 5.1.4 on 2025-02-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliments', '0001_populate_initial_data'),
        ('compliments', '0002_populate_initial_data'),
    ]

    operations = [
    ]
